BBS_Pro/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

from django.conf import settings

#import bbs.urls
#import assets.urls
#import monitor.urls
#import configManage.urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^$', 'bbs.views.dashboard', {"template_name": "dashboard.html"}),
]


# bbs message
urlpatterns += [
    url(r'^bbs/', include('bbs.urls')),
]

# config manage
urlpatterns += [
    url(r'^config/', include('configManage.urls')),
]

# assets message
urlpatterns += [
    url(r'^assets/', include('assets.urls', namespace='assets')),
]

# monitor message
urlpatterns += [
    url(r'^monitor/', include('monitor.urls')),
]


urlpatterns += [
    url(r'^auth/', include('myauth.urls', namespace='auth')),
]

# author message
urlpatterns += [
    url(r'^author/$', 'bbs.views.author', {"template_name": "author_mess.html"}),
]

# user login
urlpatterns += [
    url(r'^login/$', 'bbs.views.bbs_login', {"template_name": "login.html"}),
    url(r'^auth/$', 'bbs.views.authen'),
    url(r'^logout/$', 'bbs.views.logout'),
    url(r'^userinfo/$', 'bbs.views.userinfo'),
    url(r'^setting/$', 'bbs.views.setting'),
    url(r'^account/$', 'bbs.views.account'),
]


if settings.DEBUG:  
    urlpatterns += patterns('',  
            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':True}),  
            )

assets/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('assets.views',

    url(r'^$', 'dashboard', {"template_name": "assets_list.html"}, name='dashboard'),
    url(r'^add/$', 'add', {"template_name": "assets_add.html"}, name='add'),
    url(r'^search/$', 'search', {"template_name": "search_assets_list.html"}, name='search'),

)

bbs/urls.py
from django.conf.urls import patterns

import views

urlpatterns = patterns('bbs.views',
    (r'^$', 'index'),
    (r'(?P<bid>\d+)/details/$', 'bbs_detail'),
    #
    (r'(?P<bid>\d+)/edit/$', 'bbs_edit'),
    (r'(?P<bid>\d+)/update/$', 'update'),
    #
    (r'add/$', 'add_blog', {"template_name": "add_blog.html"}),
    (r'add_blog_pro/$', 'add_blog_pro'),
    (r'list/$', 'manage_blog_list'),
    (r'delete/(?P<bid>\d+)/$', 'delete_blog'),
    (r'search/$', 'search',  {"template_name": "bbs_search.html"}),
    (r'search_deal/$', 'search_deal'),

)

assets/models.py
#-*- coding:utf-8 -*-
from django.db import models
from bbs.models import BBS_user

import django.utils.timezone as timezone

class Host(models.Model):
    
    STATUS_CHOICE = (
                 (0, '线上'),
                 (1, '下线'),
                 )    
    
    OPERSYS_CHOICE = (
                      (0, 'CentOS6.5'),
                      (1, 'RedHat7'),
                      (2, 'Ubuntu12'),
                      (3, 'Windows2008'),
                      )
    
    ipaddr = models.GenericIPAddressField()
    hostname = models.CharField(u'主机名', max_length=50)
    status = models.IntegerField(choices=STATUS_CHOICE,
                                 default=0)
    opersys = models.IntegerField(choices = OPERSYS_CHOICE,
                                  default=0)
    supporter = models.ForeignKey(BBS_user)
    mroom = models.ForeignKey(u'Machine_Room')
    adddate = models.DateTimeField(default = timezone.now)
    updatedate = models.DateTimeField(auto_now = True)
    
    class Meta:
        verbose_name = u'IP列表'
        verbose_name_plural = verbose_name
        
    def __unicode__(self):
        return self.hostname

class Machine_Room(models.Model):
    name = models.CharField(u'机房', max_length=20)
    address = models.CharField(u'地址', max_length=200)
    telphone = models.IntegerField(u'联系人')
    email = models.EmailField(u'邮箱')
    overtime = models.DateTimeField(u'到期时间')
    
    class Meta:
        verbose_name = u'机房信息'
        verbose_name_plural = verbose_name
        
    def __unicode__(self):
        return self.name
    
    
    

assets/forms.py
#-*- coding:utf-8 -*-
'''
Created on 2016/6/19

@author: QiRui.Su schangech@gmail.com
'''

from django import forms
from django.forms import ModelForm
from django.views.generic import CreateView, UpdateView
from models import Host, Machine_Room
from bbs.models import BBS_user
from django.contrib.auth.models import User

import django.utils.timezone as timezone

#自定义form表单
#class HostForm(forms.Form):
#继承关联ORM定义的Model数据表单
class HostForm(ModelForm):
    HOST_STATUS = {
                  (1, '线上'),
                  (0, '线下'),
                  }
    OPER_SYS = {
                (0, 'CentOS6.5 x86_64'),
                (1, 'RedHat5.8 x86_64'),
                (2, 'Ubuntu11 x86 Server'),
                (3, 'Debian11 x86_64'),
                (4, 'Suse8 x86_64'),
                }
    ipaddr = forms.CharField(label=(u'IP地址'), max_length=50, required=False, widget=forms.TextInput(attrs={'type': "text", 'class': 'form-control', "placeholder":"218.30.110.192", 'style':'width:180px;height:30px'}))
    hostname = forms.CharField(label=(u'主机名'), max_length=50, required=False, widget=forms.TextInput(attrs={'class': 'form-control', "placeholder":"sjhl-o-hc01v", 'style':'width:180px;height:30px'}))
    status = forms.ChoiceField(label=(u'主机状态'), required=False, choices=HOST_STATUS, widget=forms.Select(attrs={'data-rel': 'chosen', 'style':'width:100px;'}))
    opersys = forms.ChoiceField(label=(u'操作系统选择'), required=False, choices=OPER_SYS, widget=forms.Select(attrs={'data-rel': 'chosen', 'style':'width:200px;'}))
    
    user_list = User.objects.values_list('username')
    kv_user = map(lambda mr:(mr[0], mr[0]), user_list)
    supporter = forms.ChoiceField(label=(u'运维负责人'), required=False, choices=kv_user, widget=forms.Select(attrs={'class':'control-label','data-rel': 'chosen', 'style':'width:100px;'}))
    
#   返回字典格式
#    mroom_list = Machine_Room.objects.values('name')
#   返回元祖格式
    mroom_list = Machine_Room.objects.values_list('name')
    kv_mroom = map(lambda mr:(mr[0], mr[0]), mroom_list)
    #mroom = forms.MultipleChoiceField(label=(u'机房位置'), required=False, choices=kv_mroom, widget=forms.SelectMultiple(attrs={'data-rel': 'chosen'}))
    mroom = forms.ChoiceField(label=(u'机房位置'), required=False, choices=kv_mroom, widget=forms.Select(attrs={'data-rel': 'chosen', 'style':'width:150px;'}))
    class Meta:  
        model = Host
        fields = ['ipaddr', 'hostname', 'status', 'supporter', 'mroom', 'opersys']


    def clean_supporter(self):
        user = User.objects.get(username=self.cleaned_data['supporter'])
        print user
        return BBS_user.objects.get(user = user)
    
    def clean_mroom(self):
        return Machine_Room.objects.get(name=self.cleaned_data['mroom'])
    
    
    
    
    
    
    

assets/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib.auth.decorators import login_required 
from django.db.models import Q
from models import Host, Machine_Room
from forms import HostForm

@login_required(login_url="/login/")
def dashboard(request, template_name):
    host_lists = Host.objects.all()
    return render_to_response(template_name, 
                              {'user': request.user,
                               'host_lists': host_lists,
                               }
                              )


@login_required(login_url="/login/")
def add(request, template_name):
    if request.method == 'POST':
        form = HostForm(request.POST)
        if form.is_valid():
            host_info = form.save()
            host_info.save()
            return HttpResponseRedirect('/assets/')
            #return HttpResponseRedirect('/')
    else:
        form = HostForm()
    return render_to_response(template_name, 
                              {'user': request.user,
                               'form': form,
                               }
                              )

@login_required(login_url="/login/")    
def delete(request):
    pass

@login_required(login_url="/login/")
def update(request):
    pass

@login_required(login_url="/login/")
def search(request, template_name):
    search_q = request.GET.get('search')
    host_msg_lists = Host.objects.filter(Q(ipaddr__icontains = search_q) | Q(hostname__icontains = search_q))  
    return render_to_response(template_name, 
                          {'user': request.user,
                           'host_lists': host_msg_lists,
                           }
                          )
    
    
    

assets/templates/assets_add.html
{% extends "base.html" %}  
{% load static from staticfiles %}

{% block title %}<title>添加主机</title>{% endblock %}  

    {% block staticcss %} 
	{% endblock %} 

	{% block content-page %}
<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
        
	        <form class="form-inline" role="form" action="/assets/add/" method="POST">
	        {% csrf_token %}
	            <div class="box-header well" data-original-title="">
	                <h2><i class="glyphicon glyphicon-edit"></i> 添加主机 </h2>
	
	                <div class="box-icon">
	                    <a href="#" class="btn btn-setting btn-round btn-default"><i
	                            class="glyphicon glyphicon-cog"></i></a>
	                    <a href="#" class="btn btn-minimize btn-round btn-default"><i
	                            class="glyphicon glyphicon-chevron-up"></i></a>
	                    <a href="#" class="btn btn-close btn-round btn-default"><i
	                            class="glyphicon glyphicon-remove"></i></a>
	                </div>
	            </div>
	            <div class="box-content">
	                <br>
	                
	                {% for field in form %}
	                <div class="control-group">
		                {{field.label_tag}} &nbsp;&nbsp;&nbsp; {{field}}
		                {{field.errors}}
	                    <br>
	                    <br>                
	                </div>
	                {% endfor %}
	                <br>
	                <br>
	                <button type="submit" class="btn btn-default">提交</button>
	             </div>
	         </form>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->


	{% endblock %}
	<hr>

    {% block staticjs %} 
    {% endblock %}

assets/templates/assets_list3.html
{% extends "base.html" %}  

{% block title %}<title>数据表显示</title>{% endblock %}  

    {% block staticcss %} 
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap-table.min.css">

	{% endblock %} 

	{% block content-page %}
<div class="container">
    <div>
        <label>Cells: </label><input id="cells" type="text" placeholder="Cells" value="5">
        <label>Rows: </label><input id="rows" type="text" placeholder="Rows" value="100">
        <button id="build" class="btn btn-default">Build</button>
    </div>
    <table id="table"
           data-toggle="table"
           data-url="/static/data/data1.json"
           data-show-columns="true"
           data-search="true"
           data-show-refresh="true"
           data-show-toggle="true"
           data-pagination="true"
           data-height="500">
        <thead>
        <tr>
            <th data-field="id" data-formatter="idFormatter">ID</th>
            <th data-field="name">Item Name</th>
            <th data-field="price">Item Price</th>
        </tr>
        </thead>
    </table>
</div>
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<!--<script src="assets/bootstrap2.3/js/bootstrap.min.js"></script>-->
<script src="/static/js/tableExport.js"></script>
<script src="/static/js/jquery.base64.js"></script>
<script src="/static/js/bootstrap-table.js"></script>
<script src="/static/js/bootstrap-table-export.js"></script>
<script>
    $(function () {
        $('#build').click(build);//.trigger('click');
        $('#cells, #rows').keyup(function (e) {
            if (e.keyCode === 13) {
                build();
            }
        });
    });

    function build() {
        var cells = $('#cells').val(),
            rows = $('#rows').val(),
            i, j, row,
            columns = [],
            data = [];

        for (i = 0; i < cells; i++) {
            columns.push({
                field: 'field' + i,
                title: 'Cell' + i
            });
        }
        for (i = 0; i < rows; i++) {
            row = {};
            for (j = 0; j < cells; j++) {
                row['field' + j] = 'Row-' + i + '-' + j;
            }
            data.push(row);
        }
        $('#table').bootstrapTable('destroy').bootstrapTable({
            columns: columns,
            data: data
        });
    }

    function idFormatter(value) {
        return value + 100;
    }
</script>


	{% endblock %}
      
    {% block staticjs %} 
    {% endblock %}

assets/templates/bak.html
{% extends "base.html" %}  

{% block title %}<title>数据表显示</title>{% endblock %}  

    {% block staticcss %} 
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--     <link rel="stylesheet" href="/static/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap-table.min.css"> -->

    <!-- The styles -->
    <link id="bs-css" href="/static/css/bootstrap-cerulean.min.css" rel="stylesheet">

    <link href="/static/css/charisma-app.css" rel="stylesheet">
    <link href='/static/bower_components/fullcalendar/dist/fullcalendar.css' rel='stylesheet'>
    <link href='/static/bower_components/fullcalendar/dist/fullcalendar.print.css' rel='stylesheet' media='print'>
    <link href='/static/bower_components/chosen/chosen.min.css' rel='stylesheet'>
    <link href='/static/bower_components/colorbox/example3/colorbox.css' rel='stylesheet'>
    <link href='/static/bower_components/responsive-tables/responsive-tables.css' rel='stylesheet'>
    <link href='/static/bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css' rel='stylesheet'>
    <link href='/static/css/jquery.noty.css' rel='stylesheet'>
    <link href='/static/css/noty_theme_default.css' rel='stylesheet'>
    <link href='/static/css/elfinder.min.css' rel='stylesheet'>
    <link href='/static/css/elfinder.theme.css' rel='stylesheet'>
    <link href='/static/css/jquery.iphone.toggle.css' rel='stylesheet'>
    <link href='/static/css/uploadify.css' rel='stylesheet'>
    <link href='/static/css/animate.min.css' rel='stylesheet'>

    <!-- jQuery -->
    <script src="/static/bower_components/jquery/jquery.min.js"></script>
    
	{% endblock %} 

	{% block content-page %}

                    <tr>
                        <!-- <td><h3>Dialog</h3></td> -->
                        <td>
                            <a href="#" class="btn btn-info btn-setting">添加主机</a>
                        </td>
                        <td></td>
                    </tr>

    <div class="row">
    <div class="box col-md-12">
    <div class="box-inner">
    <div class="box-header well" data-original-title="">
        <h2><i class="glyphicon glyphicon-user"></i> 主机列表 </h2>

        <div class="box-icon">
        
                    <tr>
                        <td>
                            <a href="#" class="btn btn-info btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                        </td>
                        <td></td>
                    </tr>
                    
            <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
            <a href="#" class="btn btn-minimize btn-round btn-default"><i class="glyphicon glyphicon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
        </div>
    </div>
    <div class="box-content">
    <div class="alert alert-info">For help with such table please check <a href="#" target="_blank">http://weibo.com/schangech/</a></div>
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
    <tr>
        <th>类型</th>
        <th>主机名</th>
        <th>IP</th>
        <th>操作系统</th>
        <th>负责人</th>
        <td>机房</td>
        <th>状态</th>
        <th>详情</th>
    </tr>
    </thead>
    <tbody>
    
    {% for host in host_lists %}
    <tr>
        <td>阿里·云主机</td>
        <td class="center">{{host.hostname}}</td>
        <td class="center">{{host.ipaddr}}</td>
        <td class="center">{{host.get_opersys_display}}</td>
        <td class="center">{{host.supporter}}</td>
        <td class="center">{{host.mroom}}</td>
        {% ifequal host.status 1 %}
        <td class="center">
            <span class="label-default label">{{host.get_status_display}}</span>
        </td>
        {% else %}
        <td class="center">
            <span class="label-success label label-default">{{host.get_status_display}}</span>
        </td>
        {% endifequal %}
		<td>
	        <div class="box-icon">
	        	<a href="#" class="btn btn-setting btn-round btn-default"  title="详细信息"><i class="glyphicon glyphicon-exclamation-sign"></i></a>
	        </div>
        </td>
        
        
        
<!--         <td class="center">
            <a class="btn btn-success" href="#">
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
            <a class="btn btn-info" href="#">
                <i class="glyphicon glyphicon-edit icon-white"></i>
                Edit
            </a>
            <a class="btn btn-danger" href="#">
                <i class="glyphicon glyphicon-trash icon-white"></i>
                Delete
            </a>
        </td> -->
    </tr>
    {% endfor %}
    
    
<!--  
    <tr>
        <td>阿里·云主机</td>
        <td class="center">BJ-ALIYUN-O-HC01V</td>
        <td class="center">10.20.0.3</td>
        <td class="center">Windows 2008 X86_64</td>
        <td class="center">MR.SU</td>
        <td class="center">
            <span class="label-default label">下线</span>
        </td>
         <td class="center">
            <a class="btn btn-success" href="#">
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
            <a class="btn btn-info" href="#">
                <i class="glyphicon glyphicon-edit icon-white"></i>
                Edit
            </a>
            <a class="btn btn-danger" href="#">
                <i class="glyphicon glyphicon-trash icon-white"></i>
                Delete
            </a>
        </td> 
    </tr>	
    <tr>
        <td>腾讯·云主机</td>
        <td class="center">BJ-ALIYUN-O-HC02V</td>
        <td class="center">10.20.0.4</td>
        <td class="center">CentOS 7.1 X86_64</td>
        <td class="center">MR.SU</td>
        <td class="center">
            <span class="label-success label label-default">线上</span>
        </td>
         <td class="center">
            <a class="btn btn-success" href="#">
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
            <a class="btn btn-info" href="#">
                <i class="glyphicon glyphicon-edit icon-white"></i>
                Edit
            </a>
            <a class="btn btn-danger" href="#">
                <i class="glyphicon glyphicon-trash icon-white"></i>
                Delete
            </a>
        </td> 
    </tr>-->
    </tbody>
    </table>
    </div>
    </div>
    </div>
    <!--/span-->
    </div><!--/row-->
    
    <!-- content ends -->
	{% endblock %}
	<hr>
	

                    <tr>
                        <td><h3>Dialog</h3></td>
                        <td>
                            <a href="#" class="btn btn-info btn-setting">Click for dialog</a>
                        </td>
                        <td></td>
                    </tr>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">

        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h3>Settings</h3>
                </div>
                <div class="modal-body">
                    <p>Here settings can be configured...</p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Save changes</a>
                </div>
            </div>
        </div>
    </div>
<!--     {% include 'dialog.html' %} -->
    {% block staticjs %} 
    {% endblock %}

assets/templates/search_assets_list.html
{% extends "base.html" %}  
{% load static from staticfiles %}

{% block title %}<title>数据表显示</title>{% endblock %}  

    {% block staticcss %} 
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="/static/css/bootstrap-table.min.css">

    <!-- The styles -->
    <link id="bs-css" href="{% static 'css/bootstrap-cerulean.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/charisma-app.css' %}"  rel="stylesheet">
    <link href="{% static 'bower_components/fullcalendar/dist/fullcalendar.css' %}"  rel='stylesheet'>
    <link href="{% static 'bower_components/fullcalendar/dist/fullcalendar.print.css' %}"  rel='stylesheet' media='print'>
    <link href="{% static 'bower_components/chosen/chosen.min.css' %}"  rel='stylesheet'>
    <link href="{% static 'bower_components/colorbox/example3/colorbox.css' %}"  rel='stylesheet'>
    <link href="{% static 'bower_components/responsive-tables/responsive-tables.css' %}"  rel='stylesheet'>
    <link href="{% static 'bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/jquery.noty.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/noty_theme_default.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/elfinder.min.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/elfinder.theme.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/jquery.iphone.toggle.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/uploadify.css' %}"  rel='stylesheet'>
    <link href="{% static 'css/animate.min.css' %}"  rel='stylesheet'>

    <!-- jQuery -->
    <script src="{% static 'bower_components/jquery/jquery.min.js' %}"></script>
    
	{% endblock %} 

	{% block content-page %}

     <tr>
        <td>
            <a class="btn btn-default" href="{% url 'assets:add' %}" role="button">添加主机</a>
        </td>
        <td></td>
    </tr>



    <div class="row">
    <div class="box col-md-12">
    <div class="box-inner">
    <div class="box-header well" data-original-title="">
        <h2><i class="glyphicon glyphicon-user"></i> 主机列表 </h2>

        <div class="box-icon">
        
<!--                     <tr>
                        <td>
                            <a href="#" class="btn btn-info btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
                        </td>
                        <td></td>
                    </tr> -->
                    
            <a href="#" class="btn btn-setting btn-round btn-default"><i class="glyphicon glyphicon-cog"></i></a>
            <a href="#" class="btn btn-minimize btn-round btn-default"><i class="glyphicon glyphicon-chevron-up"></i></a>
            <a href="#" class="btn btn-close btn-round btn-default"><i class="glyphicon glyphicon-remove"></i></a>
        </div>
    </div>
    <div class="box-content">
    <div class="alert alert-info">For help with such table please check <a href="#" target="_blank">http://weibo.com/schangech/</a></div>
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
    <thead>
    <tr>
        <th>类型</th>
        <th>主机名</th>
        <th>IP</th>
        <th>操作系统</th>
        <th>负责人</th>
        <td>机房</td>
        <th>状态</th>
        <th>详情</th>
    </tr>
    </thead>
    <tbody>
    
    {% for host in host_lists %}
    <tr>
        <td>阿里·云主机</td>
        <td class="center">{{host.hostname}}</td>
        <td class="center">{{host.ipaddr}}</td>
        <td class="center">{{host.get_opersys_display}}</td>
        <td class="center">{{host.supporter}}</td>
        <td class="center">{{host.mroom}}</td>
        {% ifequal host.status 1 %}
        <td class="center">
            <span class="label-default label">{{host.get_status_display}}</span>
        </td>
        {% else %}
        <td class="center">
            <span class="label-success label label-default">{{host.get_status_display}}</span>
        </td>
        {% endifequal %}
		<td>
	        	<a href="###/assets/details/{{host.pk}}" class="center"  title="详细信息"><i class="glyphicon glyphicon-zoom-in icon-white"></i></a>
        </td>
        
        
        
<!--         <td class="center">
            <a class="btn btn-success" href="#">
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
            <a class="btn btn-info" href="#">
                <i class="glyphicon glyphicon-edit icon-white"></i>
                Edit
            </a>
            <a class="btn btn-danger" href="#">
                <i class="glyphicon glyphicon-trash icon-white"></i>
                Delete
            </a>
        </td> -->
    </tr>
    {% endfor %}
    
    
<!--  
    <tr>
        <td>阿里·云主机</td>
        <td class="center">BJ-ALIYUN-O-HC01V</td>
        <td class="center">10.20.0.3</td>
        <td class="center">Windows 2008 X86_64</td>
        <td class="center">MR.SU</td>
        <td class="center">
            <span class="label-default label">下线</span>
        </td>
         <td class="center">
            <a class="btn btn-success" href="#">
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
            <a class="btn btn-info" href="#">
                <i class="glyphicon glyphicon-edit icon-white"></i>
                Edit
            </a>
            <a class="btn btn-danger" href="#">
                <i class="glyphicon glyphicon-trash icon-white"></i>
                Delete
            </a>
        </td> 
    </tr>	
    <tr>
        <td>腾讯·云主机</td>
        <td class="center">BJ-ALIYUN-O-HC02V</td>
        <td class="center">10.20.0.4</td>
        <td class="center">CentOS 7.1 X86_64</td>
        <td class="center">MR.SU</td>
        <td class="center">
            <span class="label-success label label-default">线上</span>
        </td>
         <td class="center">
            <a class="btn btn-success" href="#">
                <i class="glyphicon glyphicon-zoom-in icon-white"></i>
                View
            </a>
            <a class="btn btn-info" href="#">
                <i class="glyphicon glyphicon-edit icon-white"></i>
                Edit
            </a>
            <a class="btn btn-danger" href="#">
                <i class="glyphicon glyphicon-trash icon-white"></i>
                Delete
            </a>
        </td> 
    </tr>-->
    </tbody>
    </table>
    </div>
    </div>
    </div>
    <!--/span-->
    </div><!--/row-->
    
    {% include 'dialog.html' %}
    <!-- content ends -->
	{% endblock %}
	<hr>
	



    {% block staticjs %} 
    {% endblock %}